### ISSUE TITLE
Not able to make payment

### ISSUE THREAD

**Issue by marciovalim** [Git-RenatoAlcantara/paypal_mobile_payment#1]
Failed to handle method call
E/MethodChannel#paypal_mobile_payment(20568): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/MethodChannel#paypal_mobile_payment(20568): 	at android.content.ComponentName.<init>(ComponentName.java:130)
E/MethodChannel#paypal_mobile_payment(20568): 	at android.content.Intent.<init>(Intent.java:6108)
E/MethodChannel#paypal_mobile_payment(20568): 	at com.renato.paypal_mobile_payment.PaypalMobilePaymentPlugin.onMethodCall(PaypalMobilePaymentPlugin.java:69)
E/MethodChannel#paypal_mobile_payment(20568): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#paypal_mobile_payment(20568): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#paypal_mobile_payment(20568): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#paypal_mobile_payment(20568): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#paypal_mobile_payment(20568): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#paypal_mobile_payment(20568): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#paypal_mobile_payment(20568): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#paypal_mobile_payment(20568): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#paypal_mobile_payment(20568): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#paypal_mobile_payment(20568): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (20568): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/flutter (20568): 	at android.content.ComponentName.<init>(ComponentName.java:130)
E/flutter (20568): 	at android.content.Intent.<init>(Intent.java:6108)
E/flutter (20568): 	at com.renato.paypal_mobile_payment.PaypalMobilePaymentPlugin.onMethodCall(PaypalMobilePaymentPlugin.java:69)
E/flutter (20568): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (20568): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (20568): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (20568): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (20568): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (20568): 	at android.os.Looper.loop(Looper.java:165)
E/flutter (20568): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/flutter (20568): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (20568): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (20568): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by RodrigoRodriguez1** [comment]
I i have the same error

**Comment by zakblacki** [comment]
Same problem I replaced clientId with my own but same issue.
